package net.reichholf.dreamdroid.helpers.enigma2

object URIStore {
    const val EPG_NOW: String = "/web/epgnow?"
    const val EPG_NEXT: String = "/web/epgnext?"
    const val EPG_NOWNEXT: String = "/web/epgnownext?"
    const val EPG_SERVICE: String = "/web/epgservice?"
    const val EPG_SERVICE_NOW: String = "/web/epgservicenow?"
    const val EPG_SERVICE_NEXT: String = "/web/epgservicenext?"
    const val EPG_SEARCH: String = "/web/epgsearch?"
    const val EPG_BOUQUET: String = "/web/epgbouquet?"
    const val EPG_MULTI: String = "/web/epgmulti?"
    const val DEVICE_INFO: String = "/web/deviceinfo"
    const val SETTINGS: String = "/web/settings"
    const val SIGNAL: String = "/web/signal"
    const val SERVICES: String = "/web/getservices?"
    const val VOLUME: String = "/web/vol?"
    const val LOCATIONS: String = "/web/getlocations"
    const val LOCATIONS_CURRENT: String = "/web/getcurrlocation"
    const val CURRENT: String = "/web/getcurrent"
    const val POWERSTATE: String = "/web/powerstate?"
    const val SUBSERVICES: String = "/web/subservices"
    const val SUBSERVICES_STREAM: String = "/web/streamsubservices?"
    const val TAGS: String = "/web/gettags"
    const val MEDIA_PLAYER_PLAY: String = "/web/mediaplayerplay?"
    const val MOVIES: String = "/web/movielist?"
    const val MOVIE_DELETE: String = "/web/moviedelete?"
    const val TIMER_LIST: String = "/web/timerlist"
    const val TIMER_ADD_BY_EVENT_ID: String = "/web/timeraddbyeventid?"
    const val TIMER_CHANGE: String = "/web/timerchange?"
    const val TIMER_WRITE: String = "/web/timerlistwrite?write=saveWriteNow"
    const val TIMER_CLEANUP: String = "/web/timercleanup?cleanup=true"
    const val TIMER_DELETE: String = "/web/timerdelete?"
    const val MESSAGE: String = "/web/message?"
    const val SCREENSHOT: String = "/grab?"
    const val SESSION: String = "/web/session"
    const val SLEEPTIMER: String = "/web/sleeptimer?"
    const val FILE: String = "/file?"
    const val ZAP: String = "/web/zap?"
    const val REMOTECONTROL: String = "/web/remotecontrol?"
}
